server:
  port: 8083
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/coupondb
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
     hibernate:
      format-sql: true
      
      
      