logging:
  level:
    com:
      zensar:
        controllers: debug
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/product_db
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    user:
      name: tom
      password: tom@1234
        
server:
 servlet:
  context-path: /mycontext
  
     
      
